apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sadebo/ai-infra-azure.git'
    path: helm-charts/fastapi
    targetRevision: main
    helm:
      values: |
        image:
          repository: aiinfraacr.azurecr.io/fastapi
          tag: v1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
