# ArgoCD Applications live in the "argocd" namespace,
# but Istio will be installed into "istio-system".
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.0 # pick latest stable release
    chart: istio-base
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # 👈 auto-create istio-system
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.0
    chart: gateway
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # 👈 auto-create istio-system
    automated:
      prune: true
      selfHeal: true
