# Istio Core Components Deployment Manifest (3 in 1 File)
#
# This file contains 3 Argo CD Applications:
# 1. istio-base (CRDs) - Sync Wave 1
# 2. istiod (Control Plane) - Sync Wave 2
# 3. istio-ingressgateway (Data Plane) - Sync Wave 3

# --- 1. Istio Base (CRDs) ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy CRDs first
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.22.0
    helm:
      values: |
        defaultRevision: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
# --- 2. Istiod (Control Plane) ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Deploy Control Plane second
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.0
    helm:
      values: |
        revision: default
        # Explicitly setting the hub fixes ImagePullBackOff errors
        global:
          hub: gcr.io/istio-release
          tag: 1.22.0
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# --- 3. Istio Ingress Gateway ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Deploy Gateway last
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.22.0
    helm:
      releaseName: istio-ingressgateway
      values: |
        # Explicitly setting the global hub to match istiod
        global:
          hub: gcr.io/istio-release
          tag: 1.22.0

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        service:
          type: LoadBalancer # Use LoadBalancer for external exposure

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
