apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-infra-cert
  namespace: istio-system
spec:
  secretName: ai-infra-cert
  dnsNames:
  - "fastapi.parallelservicesllc.com"
  - "*.fastapi.parallelservicesllc.com"
  - "mlflow.parallelservicesllc.com"
  - "*.mlflow.parallelservicesllc.com"
  - "prefect.parallelservicesllc.com"
  - "*.prefect.parallelservicesllc.com"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
