apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: ["mlflow", "server",
               "--backend-store-uri", "sqlite:///mlflow.db",
               "--default-artifact-root", "file:/mlflow/artifacts",
               "--host", "0.0.0.0"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlflow/artifacts
      volumes:
      - name: mlflow-artifacts
        persistentVolumeClaim:
          claimName: mlflow-pvc
