name: Destroy AI Infra

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'yes' to confirm destroying all infrastructure"
        required: true
        default: "no"
        type: string
jobs:
  helm-cleanup:
    name: Uninstall Helm Releases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group ai-infra-rg \
          --name ai-infra-aks \
          --overwrite-existing || echo "AKS not found, skipping"

    - name: Uninstall Helm Releases
      run: |
        helm uninstall fastapi-inference || true
        helm uninstall mlflow || true
        helm uninstall prefect || true

  terraform-destroy:
    name: Terraform Destroy Infrastructure
    runs-on: ubuntu-latest
    needs: helm-cleanup
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6 # use your local TF version

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init -input=false

    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform destroy -auto-approve -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
